### ISSUE TITLE
geeting this error in your examples

### ISSUE THREAD

**Issue by Rachit-Pandey-2004** [GitBolt/solathon#12]
Traceback (most recent call last):
  File "c:\Users\hp\Desktop\fresh solana project\tester1.py", line 1, in <module>
    from solathon import Client, Keypair
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\solathon\__init__.py", line 3, in <module>
    from .client import Client
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\solathon\client.py", line 7, in <module>
    from .transaction import Transaction
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\solathon\transaction.py", line 9, in <module>
    from .core.instructions import Instruction, AccountMeta
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\solathon\core\instructions.py", line 14, in <module>
    class AccountMeta:
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\solathon\core\instructions.py", line 15, in AccountMeta
    public_key: PublicKey | str
TypeError: unsupported operand type(s) for |: 'type' and 'type'
PS C:\Users\hp\Desktop\fresh solana project>

**Comment by NewFug** [comment]
Same :(

**Comment by GitBolt** [comment]
Hey @Rachit-Pandey-2004, is it happening with all examples? Can you show me the code and your Python version?

**Comment by GitBolt** [comment]
Also apologize for late reply, was a little busy with other project, sorry!

**Comment by NewFug** [comment]
> Also apologize for late reply, was a little busy with other project, sorry!

python 3.9.6 ubuntu 20.04

example - >

from solathon import Client, PublicKey
ㅤ
client = Client("https://api.devnet.solana.com")
public_key = PublicKey("B3BhJ1nvPvEhx3hq3nfK8hx4WYcKZdbhavSobZEA44ai")
balance = Client.get_balance(public_key)
ㅤ
print(balance)

**Comment by NewFug** [comment]
Traceback (most recent call last):
  File "/1crypto/sol/check.py", line 1, in <module>
    from solathon import Client, PublicKey
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/solathon/__init_     _.py", line 3, in <module>
    from .client import Client
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/solathon/client.     py", line 7, in <module>
    from .transaction import Transaction
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/solathon/transac     tion.py", line 9, in <module>
    from .core.instructions import Instruction, AccountMeta
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/solathon/core/in     structions.py", line 14, in <module>
    class AccountMeta:
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/solathon/core/in     structions.py", line 15, in AccountMeta
    public_key: PublicKey | str
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by GitBolt** [comment]
Hey there @NewFug and @Rachit-Pandey-2004. I've identified and fixed the issue, try reinstalling the package and it should work now; latest version is 0.1.2. Thanks for raising the issue!

**Comment by NewFug** [comment]
The previous error is gone, but there is a new one 

`Traceback (most recent call last):
  File "/1crypto/sol/check.py", line 1, in <module>
    from solathon import Client, PublicKeyㅤ
ImportError: cannot import name 'PublicKeyᅠ' from 'solathon' (/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/solathon/__init__.py)`

code

from solathon import Client, PublicKeyㅤ
client = Client("https://api.devnet.solana.com")
public_key = PublicKey("B3BhJ1nvPvEhx3hq3nfK8hx4WYcKZdbhavSobZEA44ai")
balance = Client.get_balance(public_key)
print(balance)

**Comment by NewFug** [comment]
from solathon import Client, PublicKeyㅤ
client = Client("https://api.devnet.solana.com/")
public_key = PublicKey("B3BhJ1nvPvEhx3hq3nfK8hx4WYcKZdbhavSobZEA44ai")
balance = client.get_balance(public_key)
print(balance)

It was necessary to change the letter C in the 4th line to a small one and everything worked.

{'jsonrpc': '2.0', 'result': {'context': {'slot': 129212448}, 'value': 348778942                         83}, 'id': 1}

**Comment by NewFug** [comment]
Can you please give me a hint? If I want to check the balance of the real wallet, what do I enter in the client?

**Comment by NewFug** [comment]
I found the solution, thank you! https://api.mainnet-beta.solana.com

**Comment by GitBolt** [comment]
Great! Again apologize for late reply, I need to turn my email on for this haha!
